### ISSUE TITLE
Need an option to diable externalURL

### ISSUE THREAD

**Issue by WenjunMao** [jenkinsci/azure-artifact-manager-plugin#96]
### What feature do you want to see added?

In some closed networks, users are unable to view artifact files using Azure Storage's Bob SAS URL. 
An option is needed to disable the feature.

### Are you interested in contributing this feature?

yes

**Comment by timja** [comment]
Which URL would you use instead?

**Comment by WenjunMao** [comment]
#97 
We want to use the Jenkins URL. This can be implemented by disabling AzureBlobVirtualFile.toExternalURL.
